refactor: error handling and names

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # =========================================================================== #
 # Description:	Task manager for the command line
-# Synopsis:			./todo.sh <command> [<argument>...]
+# Command:			bash todo
 # =========================================================================== #
 set -euo pipefail
 set -o errtrace
@@ -12,20 +12,19 @@ readonly DONE_FILE="${DATA_DIR}/done.txt"
 
 # Arguments:
 # $1	INT - Line number
-# $1	STR - Error description (optional)
-# $2	STR - Context information (optional)
+# $2	STR - Error description (optional)
 die() {
-	local line_number="${1:-?}" description="${2:-unknown error}" context="${3:-}"
-	printf "[ERROR] %s\n" "$description" >&2
-	printf "--> %s, line %d\n" "${FUNCNAME[1]}" "$line_number" >&2
-	if [[ -n "$3" ]]; then printf "--> %s\n" "$context" >&2; fi
+	local line_num="${1:-?}" desc="${2:-unknown error}"
+	local func_stack=("${FUNCNAME[@]:1:-1}")
+	printf "[ERROR] %s\n" "$desc" >&2
+	printf "--> %s, line %d\n" "${func_stack[@]}" "$line_num" >&2
 	exit 1
 }
 
-trap 'die "$LINENO" "failed command" "$BASH_COMMAND"' ERR
+trap 'die "$LINENO" "failed command (trap)"' ERR
 
 # =========================================================================== #
-# Helpers & Utilities
+# Helper functions
 # =========================================================================== #
 
 # Arguments:
@@ -35,44 +34,46 @@ assert_task_exists() {
 	local src="${1:-}" num="${2:-}"
 	if [[ -z "$src" ]]; then die "$LINENO" "arg missing: 1) source file path"; fi
 	if [[ -z "$num" ]]; then die "$LINENO" "arg missing: 2) line number"; fi
-	if [[ ! -f "$src" ]]; then die "$LINENO" "'${src##*/}' was not found in ${DATA_DIR}"; fi
+	if [[ ! -f "$src" ]]; then
+		die "$LINENO" "'${src##*/}' was not found in ${DATA_DIR}"
+	fi
 
 	local line_count; line_count="$(wc -l < "$src")"
-	local err_loc="Parent function: ${FUNCNAME[1]}"
-
 	if [[ ! "$num" =~ ^[0-9]+$ ]]; then
-		die "$LINENO" "line number '${num}' is not an integer" "${err_loc}"
+		die "$LINENO" "line number '${num}' is not an integer"
 	elif [[ $num -gt $line_count ]]; then
-		die "$LINENO" "line '${num}' was not found in ${src##*/}" "${err_loc}"
+		die "$LINENO" "line '${num}' was not found in ${src##*/}"
 	elif [[ $num -eq 0 ]]; then
-		die "$LINENO" "line number can't be 0" "${err_loc}"
+		die "$LINENO" "line number can't be 0"
 	else return 0; fi
 }
 
 # Arguments:
 # $1	STR - Line to append
 # $2	STR - Target path: "$TODO_FILE", "$DONE_FILE"
-# $3	STR - Subcommand function name: "todo_add", "todo_done", "todo_undo"
-# $4	INT - Former line number (optional)
+# $3	INT - Former line number (optional)
 insert_task() {
-	local line="${1:-}" dest="${2:-}" func="${3:-}" num="${4:-}"
-	if [[ -z "$line" ]]; then die "$LINENO" "arg missing: 1) task string"; fi
+	local task="${1:-}" dest="${2:-}" num="${3:-}"
+	if [[ -z "$task" ]]; then die "$LINENO" "arg missing: 1) task string"; fi
 	if [[ -z "$dest" ]]; then die "$LINENO" "arg missing: 2) dest file path"; fi
-	if [[ -z "$func" ]]; then die "$LINENO" "arg missing: 3) subcommand function"; fi
-	if [[ ! -f "$dest" ]]; then die "$LINENO" "'${dest##*/}' was not found in ${DATA_DIR}"; fi
-
-	local formatted_line current_date
-	if [[ "$func" == "todo_add" || "$func" == "todo_done" ]]
-		current_date="$(date +%F)";
-		formatted_line="${current_date} ${line}"
-	elif [[ "$func" == "todo_undo" ]]; then
-		formatted_line="${line#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
-	else
-		die "$LINENO" "'${func}' is not a valid subcommand function"
+	if [[ ! -f "$dest" ]]; then
+		die "$LINENO" "'${dest##*/}' was not found in ${DATA_DIR}"
 	fi
 
-	printf "%s\n" "$formatted_line" >> "$dest"
-	if ! grep -qF "$formatted_line" "$dest"; then
+	local subcmd="${FUNCNAME[-2]}"
+	local formatted_task current_date
+
+	if [[ "$subcmd" == "todo_add" || "$subcmd" == "todo_done" ]]
+		current_date="$(date +%F)";
+		formatted_task="${current_date} ${task}"
+	elif [[ "$subcmd" == "todo_undo" ]]; then
+		formatted_task="${task#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
+	else
+		die "$LINENO" "'${subcmd}' is not a valid subcommand function"
+	fi
+
+	printf "%s\n" "$formatted_task" >> "$dest"
+	if ! grep -qF "$formatted_task" "$dest"; then
 		die "$LINENO" "failed to insert task${num:+" $num"} into ${dest##*/}"
 	fi
 }
@@ -85,7 +86,7 @@ move_lines() {
 	local src_name="${1:-}" src="${DATA_DIR}/${src_name}" arg_min="2"; shift
 	if [[ -z "$src" ]]; then die "$LINENO" "arg missing: 1) source filename"; fi
 	if [[ ! -f "$src" ]];	then
-		die "$LINENO" "'${src_name}' was not found in ${DATA_DIR}";
+		die "$LINENO" "'${src_name}' was not found in ${DATA_DIR}"
 	fi
 
 	local dest_name="" dest=""
@@ -96,14 +97,14 @@ move_lines() {
 		fi
 	fi
 
-	if [[ $# -gt 0 ]]; then die "arg missing: ${arg_min}) line number"; fi
+	if [[ $# -eq 0 ]]; then die "arg missing: ${arg_min}) line number"; fi
 
 	local line num; for num in "$@"; do
 		assert_task_exists "$src" "$num"
 		line="$(sed -n "${num}p" "$srch")"
 
 		if [[ -n "$dest" ]]; then
-			_todo_insert_line "$line" "$dest" "${FUNCNAME[1]}" "$num"
+			insert_line "$line" "$dest" "$num"
 		fi
 
 		sed -i "${num}d" "$src"
@@ -121,7 +122,7 @@ move_lines() {
 todo_help() {
 	cat <<- EOF
 	USAGE
-	./todo.sh <command> [<argument>...]
+	bash todo <command> [<argument>...]
 
 	COMMANDS
 	add   <task>
@@ -132,27 +133,27 @@ todo_help() {
 	exit 0
 }
 
-# Synopsis: ./todo.sh add <task>
+# Command: bash todo.sh add <task>
 todo_add() {
 	if [[ $# -eq 0 ]]; then die "$LINENO" "missing arguments"; fi
-	local task; task="$(awk '$1=$1' <<< "$*")"
-	_todo_insert_line "$task" "$TODO_FILE" "${FUNCNAME[0]}"
+	local task_desc; task_desc="$(awk '$1=$1' <<< "$*")"
+	insert_line "$task_desc" "$TODO_FILE"
 }
 
-# Synopsis: ./todo.sh del <file-stem> <line-number>...
+# Command: bash todo.sh del <file-stem> <line-number>...
 todo_del() {
 	if [[ $# -lt 2 ]]; then die "$LINENO" "missing arguments"; fi
 	local src_name="${1}.txt"; shift
 	move_lines "$src_name" "$@"
 }
 
-# Synopsis: ./todo.sh done <line-number>...
+# Command: bash todo.sh done <line-number>...
 todo_done() {
 	if [[ $# -eq 0 ]]; then die "$LINENO" "missing arguments"; fi
 	move_lines "todo.txt" "done.txt" "$@"
 }
 
-# Synopsis: ./todo.sh undo <line-number>...
+# Command: bash todo.sh undo <line-number>...
 todo_undo() {
 	if [[ $# -eq 0 ]]; then die "$LINENO" "missing arguments"; fi
 	move_lines "done.txt" "todo.txt" "$@"
