refactor/style: error handling and formatting

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 # =========================================================================== #
-# Description:	Task manager for the command line
-# Command:			bash todo
+# [todo] command line task manager
 # =========================================================================== #
+
 set -euo pipefail
 set -o errtrace
 
@@ -13,167 +13,167 @@ readonly DONE_FILE="${DATA_DIR}/done.txt"
 # Arguments:
 # $1	INT - Line number
 # $2	STR - Error description (optional)
+# $3	STR - Subcommand usage (optional)
 die() {
-	local line_num="${1:-?}" desc="${2:-unknown error}"
-	local func_stack=("${FUNCNAME[@]:1:-1}")
+	local lineno="${1:-?}" desc="${2:-unknown error}" usage="${3:-}"
 	printf "[ERROR] %s\n" "$desc" >&2
-	printf "--> %s, line %d\n" "${func_stack[@]}" "$line_num" >&2
+	printf "--> %s, line %d\n" "${FUNCNAME[@]:1:-1}" "$lineno" >&2
+	if [[ -n "$usage" ]]; then printf "[USAGE] %s\n" "$usage" >&2; fi
 	exit 1
 }
 
 trap 'die "$LINENO" "failed command (trap)"' ERR
 
-# =========================================================================== #
-# Helper functions
-# =========================================================================== #
+# Helper functions ========================================================== #
 
 # Arguments:
-# $1	STR - Source file path: "$TODO_FILE", "$DONE_FILE"
-# $2	INT - Line number
-assert_task_exists() {
-	local src="${1:-}" num="${2:-}"
-	if [[ -z "$src" ]]; then die "$LINENO" "arg missing: 1) source file path"; fi
-	if [[ -z "$num" ]]; then die "$LINENO" "arg missing: 2) line number"; fi
-	if [[ ! -f "$src" ]]; then
-		die "$LINENO" "'${src##*/}' was not found in ${DATA_DIR}"
-	fi
+# $1	INT - Task index
+# $2	STR - Source file path: "$TODO_FILE", "$DONE_FILE"
+validate_task_index() {
+	local index="${1:-}" src="${2:-}"
+	[[ -n "$index" ]] || die "$LINENO" "arg missing: 1) line number"
+	[[ -n "$src" ]]   || die "$LINENO" "arg missing: 2) source file path"
+	[[ -f "$src" ]]   || die "$LINENO" "'${src##*/}' was not found in ${DATA_DIR}"
 
 	local line_count; line_count="$(wc -l < "$src")"
-	if [[ ! "$num" =~ ^[0-9]+$ ]]; then
-		die "$LINENO" "line number '${num}' is not an integer"
-	elif [[ $num -gt $line_count ]]; then
-		die "$LINENO" "line '${num}' was not found in ${src##*/}"
-	elif [[ $num -eq 0 ]]; then
+	if [[ ! "$index" =~ ^[0-9]+$ ]]; then
+		die "$LINENO" "line number '${index}' is not an integer"
+	elif [[ $index -gt $line_count ]]; then
+		die "$LINENO" "line '${index}' was not found in ${src##*/}"
+	elif [[ $index -eq 0 ]]; then
 		die "$LINENO" "line number can't be 0"
 	else return 0; fi
 }
 
 # Arguments:
-# $1	STR - Line to append
+# $1	STR - String to append
 # $2	STR - Target path: "$TODO_FILE", "$DONE_FILE"
-# $3	INT - Former line number (optional)
+# $3	INT - Index number from source file (optional)
 insert_task() {
-	local task="${1:-}" dest="${2:-}" num="${3:-}"
-	if [[ -z "$task" ]]; then die "$LINENO" "arg missing: 1) task string"; fi
-	if [[ -z "$dest" ]]; then die "$LINENO" "arg missing: 2) dest file path"; fi
-	if [[ ! -f "$dest" ]]; then
-		die "$LINENO" "'${dest##*/}' was not found in ${DATA_DIR}"
-	fi
+	local input_line="${1:-}" dest="${2:-}" src_index="${3:-}"
+	[[ -n "$input_line" ]] || die "$LINENO" "arg missing: 1) task string"
+	[[ -n "$dest" ]]       || die "$LINENO" "arg missing: 2) dest file path"
+	[[ -f "$dest" ]]       || die "$LINENO" "'${dest##*/}' was not found in ${DATA_DIR}"
 
-	local subcmd="${FUNCNAME[-2]}"
-	local formatted_task current_date
+	local todo_cmd="${FUNCNAME[-2]}" task_name="task"
+	if [[ -n "$src_index" ]]; then task_name+=" ${src_index}"; fi
+	local clean_line; clean_line="$(awk '$1=$1' <<< "$input_line")"
+	local output_line="" current_date=""
 
-	if [[ "$subcmd" == "todo_add" || "$subcmd" == "todo_done" ]]
+	if [[ "$todo_cmd" == "todo_add" || "$todo_cmd" == "todo_done" ]]
 		current_date="$(date +%F)";
-		formatted_task="${current_date} ${task}"
-	elif [[ "$subcmd" == "todo_undo" ]]; then
-		formatted_task="${task#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
+		output_line="${current_date} ${clean_line}"
+	elif [[ "$todo_cmd" == "todo_undo" ]]; then
+		output_line="${clean_line#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
 	else
-		die "$LINENO" "'${subcmd}' is not a valid subcommand function"
+		die "$LINENO" "'${todo_cmd}' is not a valid command function"
 	fi
 
-	printf "%s\n" "$formatted_task" >> "$dest"
-	if ! grep -qF "$formatted_task" "$dest"; then
-		die "$LINENO" "failed to insert task${num:+" $num"} into ${dest##*/}"
+	printf "%s\n" "$output_line" >> "$dest"
+	if ! grep -qF "$output_line" "$dest"; then
+		die "$LINENO" "failed to insert ${task_name} into ${dest##*/}"
 	fi
 }
 
 # Arguments:
 # $1	STR - Source filename: "todo.txt", "done.txt"
 # $2	STR - Target filename: "todo.txt", "done.txt" (optional)
-# ...	INT - Line numbers
-move_lines() {
+# ...	INT - Task index
+move_tasks() {
 	local src_name="${1:-}" src="${DATA_DIR}/${src_name}" arg_min="2"; shift
-	if [[ -z "$src" ]]; then die "$LINENO" "arg missing: 1) source filename"; fi
-	if [[ ! -f "$src" ]];	then
-		die "$LINENO" "'${src_name}' was not found in ${DATA_DIR}"
-	fi
+	[[ -n "$src" ]] || die "$LINENO" "arg missing: 1) source filename"
+	[[ -f "$src" ]] || die "$LINENO" "'${src_name}' was not found in ${DATA_DIR}"
 
 	local dest_name="" dest=""
 	if [[ "${1:-}" =~ \.txt$ ]]; then
 		dest_name="$1"; dest="${DATA_DIR}/${dest_name}"; arg_min="3"; shift
-		if [[ "$src" == "$dest" ]];	then
-			die "$LINENO" "'${dest_name}' can't both be source and dest file"
+		if [[ "$src" == "$dest" ]]; then
+			die "$LINENO" "'${dest_name}' can't be both source and dest file"
 		fi
 	fi
 
-	if [[ $# -eq 0 ]]; then die "arg missing: ${arg_min}) line number"; fi
-
-	local line num; for num in "$@"; do
-		assert_task_exists "$src" "$num"
-		line="$(sed -n "${num}p" "$srch")"
+	[[ $# -eq 0 ]] && die "arg missing: ${arg_min}) task index"
+	local line index; for index in "$@"; do
+		validate_task_index "$index" "$src"
+		line="$(sed -n "${index}p" "$src")"
 
 		if [[ -n "$dest" ]]; then
-			insert_line "$line" "$dest" "$num"
+			insert_task "$line" "$dest" "$index"
 		fi
 
-		sed -i "${num}d" "$src"
+		sed -i "${index}d" "$src"
 		if grep -qF "$line" "$src"; then
-			die "$LINENO" "failed to remove task ${num} from ${src_name}"
+			die "$LINENO" "failed to remove task ${index} from ${src_name}"
 		fi
 	done
 }
 
-# =========================================================================== #
-# Main execution
-# =========================================================================== #
+# Main execution ============================================================ #
 
-# Synopsis: bash todo.sh help
 todo_help() {
-	cat <<- EOF
+	cat <<-EOF
 	USAGE
 	bash todo <command> [<argument>...]
 
 	COMMANDS
 	add   <task>
-	del   <file-stem> <line-number>...
-	done  <line-number>...
-	undo  <line-number>...
+	del   [todo|done] <index>...
+	done  <index>...
+	undo  <index>...
 	EOF
 	exit 0
 }
 
-# Command: bash todo.sh add <task>
 todo_add() {
-	if [[ $# -eq 0 ]]; then die "$LINENO" "missing arguments"; fi
-	local task_desc; task_desc="$(awk '$1=$1' <<< "$*")"
-	insert_line "$task_desc" "$TODO_FILE"
+	local usage="bash todo add <task>"
+	[[ $# -gt 0 ]] || die "$LINENO" "missing arguments" "$usage"
+
+	local task_input="$*"
+	insert_task "$task_input" "$TODO_FILE"
 }
 
-# Command: bash todo.sh del <file-stem> <line-number>...
 todo_del() {
-	if [[ $# -lt 2 ]]; then die "$LINENO" "missing arguments"; fi
-	local src_name="${1}.txt"; shift
-	move_lines "$src_name" "$@"
+	local usage="bash todo del [todo|done] <index>..."
+	[[ $# -gt 0 ]] || die "$LINENO" "missing arguments" "$usage"
+
+	local src_name="todo.txt"
+	if [[ "$1" == "done" || "$1" == "todo" ]]; then
+		src_name="${1}.txt"; shift
+	fi
+
+	move_tasks "$src_name" "$@"
 }
 
-# Command: bash todo.sh done <line-number>...
 todo_done() {
-	if [[ $# -eq 0 ]]; then die "$LINENO" "missing arguments"; fi
-	move_lines "todo.txt" "done.txt" "$@"
+	local usage="bash todo done <index>..."
+	[[ $# -gt 0 ]] || die "$LINENO" "missing arguments" "$usage"
+	move_tasks "todo.txt" "done.txt" "$@"
 }
 
-# Command: bash todo.sh undo <line-number>...
 todo_undo() {
-	if [[ $# -eq 0 ]]; then die "$LINENO" "missing arguments"; fi
-	move_lines "done.txt" "todo.txt" "$@"
+	local usage="bash todo undo <index>..."
+	[[ $# -gt 0 ]] || die "$LINENO" "missing arguments" "$usage"
+	move_tasks "done.txt" "todo.txt" "$@"
 }
 
 main() {
-	if [[ $# -eq 0 ]]; then todo_help; fi
+	local cmd="${1:-}"; shift
+	local usage="bash todo <command> [<argument>...]"
+	[[ $# -gt 0 ]] || die "$LINENO" "missing command" "$usage"
 
 	mkdir -p "$DATA_DIR"
 	touch "$TODO_FILE" "$DONE_FILE"
 
-	local cmd="$1"; shift
 	case "$cmd" in
-		add)	todo_add	"$@" ;;
-		del)	todo_del	"$@" ;;
-		done)	todo_done	"$@" ;;
-		undo)	todo_undo	"$@" ;;
-		help)	todo_help	"$@" ;;
-		*)		die "$LINENO" "${cmd} is not a valid command" ;;
+		add)  todo_add "$@" ;;
+		del)  todo_del "$@" ;;
+		done) todo_done "$@" ;;
+		undo) todo_undo "$@" ;;
+		help) todo_help "$@" ;;
+		*)    die "$LINENO" "${cmd} is not a valid command" ;;
 	esac
 }
 
-main "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+	main "$@"
+fi
