feat/refactor: usage snippets in error handling

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -2,22 +2,22 @@
 # =========================================================================== #
 # [todo] command line task manager
 # =========================================================================== #
-set -euo -E pipefail
+set -euo pipefail
+set -o errtrace
 
 # Arguments:
 #  $1 INT Exit code: 1, 2
-#  $2 STR Error description
-#  $3 INT Line number (optional)
+#  $2 INT Line number
+#  $3 STR Error description
 die() {
-	local code="${1:-1}"
-	local desc="${2:-An unknown error has occurred.}"
-	local lineno="${3:-?}"
+	local code="${1:-1}" lineno="${2:-?}"
+	local desc="${3:-An unknown error has occurred.}"
+	local usage="${USAGE_SNIPPETS[${FUNCNAME[-2]}]}"
 
-	printf "ERROR: %s\n" "$desc" >&2
+	printf "[ERROR] %s\n" "$desc" >&2
 	if [[ "$code" -eq 2 ]]; then
-		usage="${3:-Usage information not found. Try 'bash todo help'.}"
-		printf "--\n" >&2
-		printf "%s\n" "$usage" >&2
+		printf "Usage: bash todo %s\n" "${usage:-${USAGE_SNIPPETS[todo]}}" >&2
+		printf "Try 'bash todo help' for more information.\n" >&2
 	else
 		lineno="${3:-?}"
 		printf "Function: %s\n" "${FUNCNAME[@]:1:-1}" >&2
@@ -26,21 +26,42 @@ die() {
 	exit "$code"
 }
 
-trap 'die 1 "Command failed unexpectedly." "$LINENO"' ERR
-
-# CONSTANTS ================================================================= #
+trap 'die 1 "$LINENO" "Command failed unexpectedly."' ERR
 
 readonly APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly CONFIG_FILE="${APP_ROOT}/todo.conf"
 if [[ -f "$CONFIG_FILE" ]]; then source "$CONFIG_FILE"; fi
 
 readonly DATA_DIR="${DATA_DIR:-$APP_ROOT}"
-if ! mkdir -p "$DATA_DIR"; then
-	die 1 "Cannot create directory at ${DATA_DIR}" "$LINENO"
-fi
+readonly ARCHIVE="${DATA_DIR}/archive"
+mkdir -p "$ARCHIVE"
 
 readonly TODO_FILE="${DATA_DIR}/todo.txt"
-readonly DONE_FILE="${DATA_DIR}/done.txt"
+readonly DONE_FILE="${ARCHIVE}/done.txt"
+touch "$TODO_FILE" "$DONE_FILE"
+
+# USAGE ===================================================================== #
+
+readonly -A USAGE_SNIPPETS=(
+	["todo"]="<command> [<argument>...]"
+	["todo_add"]="add <description>"
+	["todo_del"]="del [--done] <index>..."
+	["todo_done"]="done <index>..."
+	["todo_undo"]="undo <index>..."
+)
+
+usage() {
+	cat <<-EOF
+	USAGE
+	  bash todo <command> [<argument>...]
+
+	COMMANDS
+	  add   <description>
+	  del   [--done] <index>...
+	  done  <index>...
+	  undo  <index>...
+	EOF
+}
 
 # HELPERS =================================================================== #
 
@@ -50,29 +71,29 @@ readonly DONE_FILE="${DATA_DIR}/done.txt"
 #  $3 INT Index number from source file (optional)
 insert_task() {
 	local input_line="${1:-}" dest="${2:-}" src_index="${3:-}"
-	[[ -n "$input_line" ]] || die 1 "Missing argument: \$1 Task string." "$LINENO"
-	[[ -n "$dest" ]]       || die 1 "Missing argument: \$2 Target path." "$LINENO"
-	[[ -f "$dest" ]]       || die 1 "Target file ${dest##*/} was not found in ${DATA_DIR}" "$LINENO"
+	[[ -n "$input_line" ]] || die 1 "$LINENO" "Missing argument: \$1 Task string."
+	[[ -n "$dest" ]]       || die 1 "$LINENO" "Missing argument: \$2 Target path."
+	[[ -w "$dest" ]]       || die 1 "$LINENO" "Target file ${dest##*/} was not found in ${DATA_DIR}"
 
-	local cmd="${FUNCNAME[-2]}"
+	local cmd="${FUNCNAME[-2]#todo_}"
 	local task_name="task${src_index:+ $src_index}"
 	local clean_line; clean_line="$(awk '$1=$1' <<< "$input_line")"
 	local output_line current_date
 
 	case "$cmd" in
-		todo_undo)
-			output_line="${clean_line#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
-			;;
-		todo_add|todo_done)
+		add|done)
 			current_date="$(date +%F)"
 			output_line="${current_date} ${clean_line}"
 			;;
-		*) die 1 "${todo_cmd} is not a valid command function." "$LINENO" ;;
+		undo)
+			output_line="${clean_line#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
+			;;
+		*) die 1 "$LINENO" "${todo_cmd} is not a valid command function." ;;
 	esac
 
 	printf "%s\n" "$output_line" >> "$dest"
 	if ! grep -qF "$output_line" "$dest"; then
-		die 1 "Failed to insert ${task_name} into ${dest##*/}" "$LINENO"
+		die 1 "$LINENO" "Failed to insert ${task_name} into ${dest##*/}"
 	fi
 }
 
@@ -82,24 +103,24 @@ insert_task() {
 # ... INT Task indexes
 move_tasks() {
 	local src_name="${1:-}"; shift
-	[[ -n "$src" ]] || die 1 "Missing argument: \$1 Source filename." "$LINENO"
-	[[ -f "$src" ]] || die 1 "${src_name} was not found in ${DATA_DIR}" "$LINENO"
-
-	local dest_name=""
-	if [[ "${1:-}" =~ \.txt$ ]]; then dest_name="$1"; shift; fi
-
 	local src="${DATA_DIR}/${src_name}"
-	local dest="${dest_name:+${DATA_DIR}/${dest_name}}"
+	[[ -n "$src_name" ]] || die 1 "$LINENO" "Missing argument: \$1 Source filename."
 
-	[[ $# -gt 0 ]] || die 1 "Missing argument: Task indexes." "$LINENO"
+	local dest_name="" dest
+	if [[ "${1:-}" =~ \.txt$ ]]; then
+		dest_name="$1"; shift
+		dest="${dest_name:+${DATA_DIR}/${dest_name}}"
+	fi
+
+	[[ $# -gt 0 ]] || die 1 "$LINENO" "Missing argument: Task indexes."
 	local line_count; line_count="$(wc -l < "$src")"
 
 	# TODO: sort tasks / make sure the index stays correct as lines get removed
 
 	local line index; for index in "$@"; do
-		[[ "$index" =~ ^[0-9]+$ ]] || die 2 "${index} is not an integer."
-		(( index != 0 ))           || die 2 "Task index can't be zero."
-		(( index <= line_count ))  || die 2 "Task ${index} was not found in ${src_name}"
+		[[ "$index" =~ ^[0-9]+$ ]] || die 2 "$LINENO" "${index} is not an integer."
+		(( index != 0 ))           || die 2 "$LINENO" "Task index can't be zero."
+		(( index <= line_count ))  || die 2 "$LINENO" "Task ${index} was not found in ${src_name}"
 
 		line="$(sed -n "${index}p" "$src")"
 		if [[ -n "$dest" ]]; then
@@ -108,7 +129,7 @@ move_tasks() {
 
 		sed -i "${index}d" "$src"
 		if grep -qF "$line" "$src"; then
-			die 1 "Failed to remove task ${index} from ${src_name}" "$LINENO"
+			die 1 "$LINENO" "Failed to remove task ${index} from ${src_name}"
 		fi
 	done
 }
@@ -116,59 +137,41 @@ move_tasks() {
 # MAIN EXECUTION ============================================================ #
 
 todo_help() {
-	cat <<-EOF
-	USAGE
-	bash todo <command> [<argument>...]
-
-	COMMANDS
-	add   <task-description>
-	del   [todo|done] <task-index>...
-	done  <task-index>...
-	undo  <task-index>...
-	EOF
-	exit 0
+	usage; exit 0
 }
 
 todo_add() {
-	local usage="USAGE: bash todo add <task-description>"
-	[[ $# -gt 0 ]] || die 2 "Task description cannot be empty." "$usage"
+	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task description cannot be empty."
 	insert_task "$*" "$TODO_FILE"
 }
 
 todo_del() {
 	local src_name="todo.txt"
-	if [[ "${1:-}" == "done" || "${1:-}" == "todo" ]]; then
-		src_name="${1}.txt"; shift
-	fi
-
-	local usage="USAGE: bash todo del [todo|done] <task-index>..."
-	[[ $# -gt 0 ]] || die 2 "Task index required." "$usage"
+	if [[ "${1:-}" == "--done" ]]; then src_name="done.txt"; shift; fi
+	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task index required."
 	move_tasks "$src_name" "$@"
 }
 
 todo_done() {
-	local usage="USAGE: bash todo done <task-index>..."
-	[[ $# -gt 0 ]] || die 2 "Task index required." "$usage"
+	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task index required."
 	move_tasks "todo.txt" "done.txt" "$@"
 }
 
 todo_undo() {
-	local usage="USAGE: bash todo undo <task-index>..."
-	[[ $# -gt 0 ]] || die 2 "Task index required." "$usage"
+	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task index required."
 	move_tasks "done.txt" "todo.txt" "$@"
 }
 
 main() {
-	local cmd="${1:-}"; shift
 	if [[ $# -eq 0 ]]; then todo_help; fi
-
+	local cmd="${1:-}"; shift
 	case "$cmd" in
 		add)  todo_add  "$@" ;;
 		del)  todo_del  "$@" ;;
 		done) todo_done "$@" ;;
 		undo) todo_undo "$@" ;;
 		help) todo_help "$@" ;;
-		*)    die 2 "'${cmd}' is not a valid command." ;;
+		*)    die 2 "$LINENO" "'${cmd}' is not a valid command." ;;
 	esac
 }
 
