feat: rewrite of current subcommands - add, del, done, undo

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -1,166 +1,160 @@
 #!/usr/bin/env bash
 # =========================================================================== #
-# [todo] command line task manager
-# =========================================================================== #
+# Description: Portable task manager for the command line.
+# Synopsis:    bash todo <command> [<argument>...]
+
+# ERROR HANDLERS ============================================================ #
+
 set -euo pipefail
 set -o errtrace
 
-# Arguments:
-#  $1 INT Exit code: 1, 2
-#  $2 INT Line number
-#  $3 STR Error description
 die() {
-	local code="${1:-1}" lineno="${2:-?}"
-	local desc="${3:-An unknown error has occurred.}"
-	local usage="${USAGE_SNIPPETS[${FUNCNAME[-2]}]}"
+	local code="${1:-1}"
+	local desc="${2:-An unknown error has occurred.}"
+	local line_no="${3:+, line $3}"
 
-	printf "[ERROR] %s\n" "$desc" >&2
+	printf "ERROR: %s\n" "$desc" >&2
 	if [[ "$code" -eq 2 ]]; then
-		printf "Usage: bash todo %s\n" "${usage:-${USAGE_SNIPPETS[todo]}}" >&2
 		printf "Try 'bash todo help' for more information.\n" >&2
 	else
-		lineno="${3:-?}"
-		printf "Function: %s\n" "${FUNCNAME[@]:1:-1}" >&2
-		printf "Line number: %d\n" "$lineno" >&2
+		printf "--> %s%s\n" "${FUNCNAME[@]:1:-1}" "$line_no" >&2
 	fi
 	exit "$code"
 }
 
-trap 'die 1 "$LINENO" "Command failed unexpectedly."' ERR
+trap 'die 1 "Command failed unexpectedly." "$LINENO"' ERR
+
+# SETTINGS ================================================================== #
 
 readonly APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
 readonly CONFIG_FILE="${APP_ROOT}/todo.conf"
 if [[ -f "$CONFIG_FILE" ]]; then source "$CONFIG_FILE"; fi
 
 readonly DATA_DIR="${DATA_DIR:-$APP_ROOT}"
-readonly ARCHIVE="${DATA_DIR}/archive"
-mkdir -p "$ARCHIVE"
+if [[ "$DATA_DIR" != "$APP_ROOT" ]]; then
+	mkdir -p "$DATA_DIR" || die 1 "Could not create directory at ${DATA_DIR}."
+fi
 
 readonly TODO_FILE="${DATA_DIR}/todo.txt"
-readonly DONE_FILE="${ARCHIVE}/done.txt"
-touch "$TODO_FILE" "$DONE_FILE"
+if [[ ! -f "$TODO_FILE" ]]; then touch "$TODO_FILE"; fi
+[[ -r "$TODO_FILE" ]] || die 1 "Permission denied: Cannot read todo.txt."
+[[ -w "$TODO_FILE" ]] || die 1 "Permission denied: Cannot write to todo.txt."
 
-# USAGE ===================================================================== #
+readonly DISABLE_EMOJIS="${DISABLE_EMOJIS:-false}"
 
-readonly -A USAGE_SNIPPETS=(
-	["todo"]="<command> [<argument>...]"
-	["todo_add"]="add <description>"
-	["todo_del"]="del [--done] <index>..."
-	["todo_done"]="done <index>..."
-	["todo_undo"]="undo <index>..."
-)
+# UTILITIES ================================================================= #
 
-usage() {
+MARK_ADD="✨"
+MARK_DEL="🗑️"
+MARK_DONE="✅"
+MARK_UNDO="↩️"
+
+if [[ "$DISABLE_EMOJIS" == "true" ]]; then
+	MARK_ADD="[+]"
+	MARK_DEL="[-]"
+	MARK_DONE="[x]"
+	MARK_UNDO="[ ]"
+fi
+
+TODO_LINE_COUNT="$(wc -l < "$TODO_FILE")"
+INDEX_WIDTH="${#TODO_LINE_COUNT}"
+
+is_index_valid() {
+	if [[ ! "$1" =~ ^[0-9]+$ || $1 -eq 0 || $1 -gt "$TODO_LINE_COUNT" ]]; then
+		printf "%s is not a valid number.\n"; return 1
+	fi
+}
+
+# SUBCOMMANDS =============================================================== #
+
+todo_help() {
 	cat <<-EOF
 	USAGE
 	  bash todo <command> [<argument>...]
 
 	COMMANDS
 	  add   <description>
-	  del   [--done] <index>...
+	  del   <index>...
 	  done  <index>...
 	  undo  <index>...
 	EOF
-}
-
-# HELPERS =================================================================== #
-
-# Arguments:
-#  $1 STR Task string to append
-#  $2 STR Target path: "$TODO_FILE", "$DONE_FILE"
-#  $3 INT Index number from source file (optional)
-insert_task() {
-	local input_line="${1:-}" dest="${2:-}" src_index="${3:-}"
-	[[ -n "$input_line" ]] || die 1 "$LINENO" "Missing argument: \$1 Task string."
-	[[ -n "$dest" ]]       || die 1 "$LINENO" "Missing argument: \$2 Target path."
-	[[ -w "$dest" ]]       || die 1 "$LINENO" "Target file ${dest##*/} was not found in ${DATA_DIR}"
-
-	local cmd="${FUNCNAME[-2]#todo_}"
-	local task_name="task${src_index:+ $src_index}"
-	local clean_line; clean_line="$(awk '$1=$1' <<< "$input_line")"
-	local output_line current_date
-
-	case "$cmd" in
-		add|done)
-			current_date="$(date +%F)"
-			output_line="${current_date} ${clean_line}"
-			;;
-		undo)
-			output_line="${clean_line#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] }"
-			;;
-		*) die 1 "$LINENO" "${todo_cmd} is not a valid command function." ;;
-	esac
-
-	printf "%s\n" "$output_line" >> "$dest"
-	if ! grep -qF "$output_line" "$dest"; then
-		die 1 "$LINENO" "Failed to insert ${task_name} into ${dest##*/}"
-	fi
-}
-
-# Arguments:
-#  $1 STR Source filename: "todo.txt", "done.txt"
-#  $2 STR Target filename: "todo.txt", "done.txt" (optional)
-# ... INT Task indexes
-move_tasks() {
-	local src_name="${1:-}"; shift
-	local src="${DATA_DIR}/${src_name}"
-	[[ -n "$src_name" ]] || die 1 "$LINENO" "Missing argument: \$1 Source filename."
-
-	local dest_name="" dest
-	if [[ "${1:-}" =~ \.txt$ ]]; then
-		dest_name="$1"; shift
-		dest="${dest_name:+${DATA_DIR}/${dest_name}}"
-	fi
-
-	[[ $# -gt 0 ]] || die 1 "$LINENO" "Missing argument: Task indexes."
-	local line_count; line_count="$(wc -l < "$src")"
-
-	# TODO: sort tasks / make sure the index stays correct as lines get removed
-
-	local line index; for index in "$@"; do
-		[[ "$index" =~ ^[0-9]+$ ]] || die 2 "$LINENO" "${index} is not an integer."
-		(( index != 0 ))           || die 2 "$LINENO" "Task index can't be zero."
-		(( index <= line_count ))  || die 2 "$LINENO" "Task ${index} was not found in ${src_name}"
-
-		line="$(sed -n "${index}p" "$src")"
-		if [[ -n "$dest" ]]; then
-			insert_task "$line" "$dest" "$index"
-		fi
-
-		sed -i "${index}d" "$src"
-		if grep -qF "$line" "$src"; then
-			die 1 "$LINENO" "Failed to remove task ${index} from ${src_name}"
-		fi
-	done
-}
-
-# MAIN EXECUTION ============================================================ #
-
-todo_help() {
-	usage; exit 0
+	exit 0
 }
 
 todo_add() {
-	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task description cannot be empty."
-	insert_task "$*" "$TODO_FILE"
+	[[ $# -gt 0 ]] || die 2 "Task description cannot be empty."
+	local task; task="$(awk '$1=$1' <<< "$*")"
+	local index; index="$(( ${TODO_LINE_COUNT} + 1 ))"
+	printf "%s\n" "$task" >> "$TODO_FILE"
+	printf "%s %-*d %s\n" "$MARK_ADD" "$INDEX_WIDTH" "$index" "$task"
 }
 
 todo_del() {
-	local src_name="todo.txt"
-	if [[ "${1:-}" == "--done" ]]; then src_name="done.txt"; shift; fi
-	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task index required."
-	move_tasks "$src_name" "$@"
+	[[ $# -gt 0 ]] || die 2 "Task index required."
+	local task formatted_task valid_tasks="" sed_args=()
+
+	local i; for i in "$@"; do
+		if ! is_index_valid "$i"; then continue; fi
+		task="$(sed -n "${index}p" "$TODO_FILE")"
+		printf -v formatted_task "%s %-*d %s\n" "$MARK_DEL" "$INDEX_WIDTH" "$i" "$task"
+		sed_args+=("-e" "${i}d")
+		valid_tasks+="$formatted_task"
+	done
+
+	if [[ "${#sed_args[@]}" -gt 0 ]]; then
+		sed -i "${sed_args[@]}" "$TODO_FILE"
+		printf "%s" "$valid_tasks"
+	fi
 }
 
 todo_done() {
-	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task index required."
-	move_tasks "todo.txt" "done.txt" "$@"
+	[[ $# -gt 0 ]] || die 2 "Task index required."
+	local task formatted_task valid_tasks="" sed_args=()
+
+	local i; for i in "$@"; do
+		if ! is_index_valid "$i"; then continue; fi
+		task="$(sed -n "${i}p" "$TODO_FILE")"
+
+		if [[ "$task" =~ ^x ]]; then
+			printf "Task %d is already marked as done.\n" "$i"; continue
+		fi
+
+		printf -v formatted_task "%s %-*d %s\n" "$MARK_DONE" "$INDEX_WIDTH" "$i" "$task"
+		sed_args+=("-e" "${i}s/^/x /")
+		valid_tasks+="$formatted_task"
+	done
+
+	if [[ "${#sed_args[@]}" -gt 0 ]]; then
+		sed -i "${sed_args[@]}" "$TODO_FILE"
+		printf "%s" "$valid_tasks"
+	fi
 }
 
 todo_undo() {
-	[[ $# -gt 0 ]] || die 2 "$LINENO" "Task index required."
-	move_tasks "done.txt" "todo.txt" "$@"
+	[[ $# -gt 0 ]] || die 2 "Task index required."
+	local task formatted_task valid_tasks="" sed_args=()
+
+	local i; for i in "$@"; do
+		if ! is_index_valid "$i"; then continue; fi
+		task="$(sed -n "${i}p" "$TODO_FILE")"
+
+		if [[ ! "$task" =~ ^x ]]; then
+			printf "Task %d is already unchecked.\n" "$i"; continue
+		fi
+
+		printf -v formatted_task "%s %-*d %s\n" "$MARK_UNDO" "$INDEX_WIDTH" "$i" "$task"
+		sed_args+=("-e" "${i}s/^x //")
+		valid_tasks+="$formatted_task"
+	done
+
+	if [[ "${#sed_args[@]}" -gt 0 ]]; then
+		sed -i "${sed_args[@]}" "$TODO_FILE"
+		printf "%s" "$valid_tasks"
+	fi
 }
+
+# MAIN ====================================================================== #
 
 main() {
 	if [[ $# -eq 0 ]]; then todo_help; fi
@@ -171,7 +165,7 @@ main() {
 		done) todo_done "$@" ;;
 		undo) todo_undo "$@" ;;
 		help) todo_help "$@" ;;
-		*)    die 2 "$LINENO" "'${cmd}' is not a valid command." ;;
+		*)    die 2 "${cmd} is not a valid command." ;;
 	esac
 }
 
