feat: removed read user input if no argument for add and delete

diff --git a/src/add b/src/add
--- a/src/add
+++ b/src/add
@@ -11,14 +11,14 @@
 # ===================================================================================== #
 
 add_tasks() {
+	if [[ $# -eq 0 ]]
+	then
+		echo "error: argument required"
+		exit 1
+	fi
+
 	local input_str="$*"
 	local new_tasks
-
-	# If no tasks
-	while [[ -z $input_str ]]
-	do
-		read input_str
-	done
 
 	# Format tasks
 	new_tasks=$(sed "s/[[:space:]]*+[[:space:]]*/\n/g" <<< $input_str)
diff --git a/src/delete b/src/delete
--- a/src/delete
+++ b/src/delete
@@ -18,12 +18,11 @@ shopt -s extglob
 # ===================================================================================== #
 
 delete_tasks() {
-	# If no parameters // TO BE REMOVED
-	while [[ -z $1 ]]
-	do
-		local input
-		read -a input && set -- "${input[@]}"
-	done
+	if [[ $# -eq 0 ]]
+	then
+		echo "error: argument required"
+		exit 1
+	fi
 
 	local total_deleted_lines=$#
 	local file_path="$TODO_TXT"
